package burp;

import javax.swing.*;
import java.awt.*;

public class BurpPanel {
    protected JPanel panel1;
    protected JTextField directoryField;
    protected JButton directoryButton;
    protected JButton reloadButton;
    protected JTable profileTable;
    public JButton invertButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel3, gbc);
        directoryField = new JTextField();
        directoryField.setColumns(50);
        directoryField.setEditable(false);
        panel3.add(directoryField);
        directoryButton = new JButton();
        directoryButton.setText("Directory");
        panel3.add(directoryButton);
        reloadButton = new JButton();
        reloadButton.setText("Reload");
        panel3.add(reloadButton);
        invertButton = new JButton();
        invertButton.setText("Invert");
        panel3.add(invertButton);
        final JSeparator separator1 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(separator1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel2.add(scrollPane1, gbc);
        profileTable = new JTable();
        profileTable.setAutoCreateRowSorter(true);
        profileTable.setAutoResizeMode(4);
        profileTable.setCellSelectionEnabled(true);
        scrollPane1.setViewportView(profileTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
